{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.clusterIssuerName | quote }}
spec:
  acme:
    email: {{ .Values.certManager.email | quote }}
    server: {{ .Values.certManager.server | quote }}
    privateKeySecretRef:
      name: {{ .Values.certManager.privateKeySecretName | quote }}
    solvers:
      - http01:
          ingress:
            class: {{ .Values.ingress.className | default "nginx" | quote }}
{{- end }}
