{{- if .Values.ingress.enabled }}
{{- $tlsHosts := list }}
{{- if and .Values.front.enabled .Values.ingress.host }}
  {{- $tlsHosts = append $tlsHosts .Values.ingress.host }}
{{- end }}
{{- if and .Values.web.enabled .Values.web.host }}
  {{- $tlsHosts = append $tlsHosts .Values.web.host }}
{{- end }}
{{- if .Values.ingress.apiHost }}
  {{- $tlsHosts = append $tlsHosts .Values.ingress.apiHost }}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.certManager.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.certManager.clusterIssuerName | quote }}
    {{- end }}
    {{- if .Values.ingress.enableConfigurationSnippet }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      try_files $uri $uri/ /index.html;
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" | quote }}
  {{- if and .Values.ingress.tls.enabled (gt (len $tlsHosts) 0) }}
  tls:
    - hosts:
        {{- range $tlsHosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .Values.ingress.tls.secretName | quote }}
  {{- end }}
  rules:
    {{- if and .Values.front.enabled .Values.ingress.host }}
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-front
                port:
                  number: {{ .Values.front.servicePort }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-api
                port:
                  number: {{ .Values.api.servicePort }}
    {{- end }}
    {{- if and .Values.web.enabled .Values.web.host }}
    - host: {{ .Values.web.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-web
                port:
                  number: {{ .Values.web.servicePort }}
    {{- end }}
    {{- if .Values.ingress.apiHost }}
    - host: {{ .Values.ingress.apiHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-api
                port:
                  number: {{ .Values.api.servicePort }}
    {{- end }}
{{- end }}
