{{- if .Values.ingress.enabled }}
{{- $frontEnabled := default true .Values.front.enabled }}
{{- $webEnabled := default true .Values.web.enabled }}
{{- $frontHost := default .Values.ingress.host .Values.ingress.frontHost }}
{{- $webHost := .Values.ingress.webHost }}
{{- $apiHost := .Values.ingress.apiHost }}
{{- $tlsHosts := list }}
{{- if and $frontHost $frontEnabled }}{{- $tlsHosts = append $tlsHosts $frontHost }}{{- end }}
{{- if and $webHost $webEnabled }}{{- $tlsHosts = append $tlsHosts $webHost }}{{- end }}
{{- if $apiHost }}{{- $tlsHosts = append $tlsHosts $apiHost }}{{- end }}
{{- $tlsHosts = uniq $tlsHosts }}
{{- $catchAllService := "" }}
{{- $catchAllPort := 80 }}
{{- if $frontEnabled }}
  {{- $catchAllService = printf "%s-front" .Release.Name }}
  {{- $catchAllPort = .Values.front.servicePort }}
{{- else if $webEnabled }}
  {{- $catchAllService = printf "%s-web" .Release.Name }}
  {{- $catchAllPort = .Values.web.servicePort }}
{{- end }}
{{- if or $frontEnabled $webEnabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-web
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.certManager.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.certManager.clusterIssuerName | quote }}
    {{- end }}
    {{- if .Values.ingress.enableConfigurationSnippet }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      try_files $uri $uri/ /index.html;
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" | quote }}
  {{- if and (gt (len $tlsHosts) 0) .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        {{- range $tlsHosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .Values.ingress.tls.secretName | quote }}
  {{- end }}
  rules:
    {{- if and $frontEnabled $frontHost }}
    - host: {{ $frontHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ printf "%s-front" .Release.Name }}
                port:
                  number: {{ .Values.front.servicePort }}
    {{- end }}
    {{- if and $webEnabled $webHost }}
    - host: {{ $webHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ printf "%s-web" .Release.Name }}
                port:
                  number: {{ .Values.web.servicePort }}
    {{- end }}
    {{- if $catchAllService }}
    # Catch-all rule so ingress IP works without Host header
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $catchAllService }}
                port:
                  number: {{ $catchAllPort }}
    {{- end }}
{{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.certManager.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.certManager.clusterIssuerName | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" | quote }}
  {{- if and (gt (len $tlsHosts) 0) .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        {{- range $tlsHosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .Values.ingress.tls.secretName | quote }}
  {{- end }}
  rules:
    {{- if and $frontEnabled $frontHost }}
    - host: {{ $frontHost | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-api
                port:
                  number: {{ .Values.api.servicePort }}
    {{- end }}
    {{- if and $webHost $webEnabled }}
    - host: {{ $webHost | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-api
                port:
                  number: {{ .Values.api.servicePort }}
    {{- end }}
    {{- if $apiHost }}
    - host: {{ $apiHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-api
                port:
                  number: {{ .Values.api.servicePort }}
    {{- end }}
    # Catch-all rule so ingress IP works without Host header
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-api
                port:
                  number: {{ .Values.api.servicePort }}
{{- end }}
